(ns alexa-to-aurora.sql-select-basic-data
  (:require [datomic.api :as d])
 )

(def sql-select-basic-data
{
:et-Address "(korma.core/select 'Address (korma.core/fields :AddressLine1 :AddressLine2 :City :ContactName :CreatedOn :DeletedOn :Id :ModifiedOn :PostalCode :State))"
:et-Address_History "(korma.core/select 'Address_History (korma.core/fields :AddressLine1 :AddressLine2 :City :ContactName :CountryId :CreatedOn :DeletedOn :Id :ModifiedOn :PostalCode :State :TimeZoneId))"
:et-Analysis "(korma.core/select 'Analysis (korma.core/fields :CreatedOn :DeletedOn :Description :EffectiveDate :ExcludeGroupResults :Id :IncludeAssessmentScores :IncludeExposures :IncludeThreats :IncludeVulnerabilities :ModifiedOn :Name))"
:et-AnalysisAnalysis "(korma.core/select 'AnalysisAnalysis (korma.core/fields :CreatedOn :DeletedOn :DisplayIndex :Id :ModifiedOn))"
:et-AnalysisAssetLikelihood "(korma.core/select 'AnalysisAssetLikelihood (korma.core/fields :BasisValue :Comments :CreatedOn :DeletedOn :Id :Manual_BasisValue :Manual_EnteredOn :ModifiedOn :RiskBasisValue :ScoreCount :VulnerabilityCount))"
:et-AnalysisAssetVulnSeverity "(korma.core/select 'AnalysisAssetVulnSeverity (korma.core/fields :AssetCount :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-AnalysisBasis "(korma.core/select 'AnalysisBasis (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AnalysisComponentScore "(korma.core/select 'AnalysisComponentScore (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn :Score))"
:et-AnalysisExpense "(korma.core/select 'AnalysisExpense (korma.core/fields :Amount :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-AnalysisMethod "(korma.core/select 'AnalysisMethod (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AnalysisType "(korma.core/select 'AnalysisType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-ApprovalStatus "(korma.core/select 'ApprovalStatus (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :FixedEntry :ForeColorName :Id :ModifiedOn :Name))"
:et-Asset "(korma.core/select 'Asset (korma.core/fields :AssetOrigin :CreatedOn :DeletedOn :Description :DomainName :ExternalKey :Hostname :Id :IP_UInt128 :IPv6 :KeyField :MAC_Address :ModifiedOn :NetBIOSName :Url))"
:et-Asset_History "(korma.core/select 'Asset_History (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-AssetExposure "(korma.core/select 'AssetExposure (korma.core/fields :CreatedOn :DeletedOn :ExposureValue :Id :ModifiedOn :Port))"
:et-AssetExposureMitigationStatus "(korma.core/select 'AssetExposureMitigationStatus (korma.core/fields :Comments :CreatedOn :DeletedOn :ExpiresOn :Id :ModifiedOn))"
:et-AssetFilter "(korma.core/select 'AssetFilter (korma.core/fields :AssetKey :CreatedOn :DeletedOn :DomainName :Hostname :Id :IncludeDeleted :IPAddress :ModifiedOn :RemainingOnly))"
:et-AssetGroup "(korma.core/select 'AssetGroup (korma.core/fields :CreatedOn :DeletedOn :Description :ExternalKey :Id :ModifiedOn :Name))"
:et-AssetGroupBusinessMetric "(korma.core/select 'AssetGroupBusinessMetric (korma.core/fields :Amount :CreatedOn :DeletedOn :EffectiveDate :Id :ModifiedOn))"
:et-AssetGroupType "(korma.core/select 'AssetGroupType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AssetImpact "(korma.core/select 'AssetImpact (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-AssetClass "(korma.core/select 'AssetClass (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :Importance :ModifiedOn :Name))"
:et-AssetType "(korma.core/select 'AssetType (korma.core/fields :Abbreviation :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AssetVulnerability "(korma.core/select 'AssetVulnerability (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Port))"
:et-AssetVulnerabilityAddendum "(korma.core/select 'AssetVulnerabilityAddendum (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Title))"
:et-AssetVulnerabilityMitigationStatus "(korma.core/select 'AssetVulnerabilityMitigationStatus (korma.core/fields :Comments :CreatedOn :DeletedOn :ExpiresOn :Id :ModifiedOn))"
:et-AssetVulnerabilityTechnicalScan "(korma.core/select 'AssetVulnerabilityTechnicalScan (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-Attribute "(korma.core/select 'Attribute (korma.core/fields :AttributeType :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AttributeValue "(korma.core/select 'AttributeValue (korma.core/fields :CreatedOn :CurrencyValue :DateValue :DeletedOn :DoubleValue :Id :IntValue :ModifiedOn :StringValue))"
:et-AttributeValueScope "(korma.core/select 'AttributeValueScope (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AttributeValueType "(korma.core/select 'AttributeValueType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-AuditPlan "(korma.core/select 'AuditPlan (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-BusinessMetric "(korma.core/select 'BusinessMetric (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-BusinessUnit "(korma.core/select 'BusinessUnit (korma.core/fields :Abbreviation :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-BusinessUnitBusinessMetric "(korma.core/select 'BusinessUnitBusinessMetric (korma.core/fields :Amount :CreatedOn :DeletedOn :EffectiveDate :Id :ModifiedOn))"
:et-BusinessUnitBusinessUnit "(korma.core/select 'BusinessUnitBusinessUnit (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-BusinessUnitRelationshipType "(korma.core/select 'BusinessUnitRelationshipType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-ContentType "(korma.core/select 'ContentType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Country "(korma.core/select 'Country (korma.core/fields :CountryCode :CreatedOn :DeletedOn :Id :ModifiedOn :Name))"
:et-Currency "(korma.core/select 'Currency (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Name :Symbol))"
:et-CurrencyExchange "(korma.core/select 'CurrencyExchange (korma.core/fields :CreatedOn :DeletedOn :EffectiveDate :ExchangeRate :Id :ModifiedOn))"
:et-DataClass "(korma.core/select 'DataClass (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-DataFile "(korma.core/select 'DataFile (korma.core/fields :CreatedOn :DeletedOn :Extension :Filename :FromHost :Id :Length :ModifiedOn :OriginalPath))"
:et-DataFinding "(korma.core/select 'DataFinding (korma.core/fields :CreatedOn :DeletedOn :FoundOn :Id :ModifiedOn :Path))"
:et-DataFindingAddendum "(korma.core/select 'DataFindingAddendum (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Title))"
:et-DataFindingRule "(korma.core/select 'DataFindingRule (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-DataFindingMitigationStatus "(korma.core/select 'DataFindingMitigationStatus (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-DataFindingSourceType "(korma.core/select 'DataFindingSourceType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-DataFindingTechnicalScan "(korma.core/select 'DataFindingTechnicalScan (korma.core/fields :CreatedOn :DeletedOn :Id :MatchCount :ModifiedOn))"
:et-DataLocation "(korma.core/select 'DataLocation (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :Path))"
:et-DataLocationType "(korma.core/select 'DataLocationType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-DataType "(korma.core/select 'DataType (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-DetectionStatus "(korma.core/select 'DetectionStatus (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-DetectionType "(korma.core/select 'DetectionType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-EffortCategory "(korma.core/select 'EffortCategory (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-EntityType "(korma.core/select 'EntityType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-EventHistory "(korma.core/select 'EventHistory (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Title))"
:et-EventModule "(korma.core/select 'EventModule (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-EventType "(korma.core/select 'EventType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-ExpenseCategory "(korma.core/select 'ExpenseCategory (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Explanation "(korma.core/select 'Explanation (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Title))"
:et-ExplanationCategory "(korma.core/select 'ExplanationCategory (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Exposure "(korma.core/select 'Exposure (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :Number :Probability))"
:et-ExposureCategory "(korma.core/select 'ExposureCategory (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-GlobalSettings "(korma.core/select 'GlobalSettings (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Name))"
:et-Impact "(korma.core/select 'Impact (korma.core/fields :Amount :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :Value))"
:et-ImpactType "(korma.core/select 'ImpactType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-ImportData "(korma.core/select 'ImportData (korma.core/fields :CreatedOn :DeletedOn :DocType :Guid :Id :ModifiedOn :Name :Timestamp :Version))"
:et-ImporterSettings "(korma.core/select 'ImporterSettings (korma.core/fields :CreatedBy_PersonId :CreatedOn :DeletedOn :Id :ImporterKey :MapTypeKey :ModifiedOn :Name))"
:et-Incident "(korma.core/select 'Incident (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Name :NotifyEmail :NotifyRequested :OccurredOn :ReportedBy :ReportedOn))"
:et-IncidentField "(korma.core/select 'IncidentField (korma.core/fields :CreatedOn :DeletedOn :Description :Id :IsRequired :ModifiedOn :Name))"
:et-IncidentFieldData "(korma.core/select 'IncidentFieldData (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-IncidentImpact "(korma.core/select 'IncidentImpact (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-IncidentIncidentStatus "(korma.core/select 'IncidentIncidentStatus (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-IncidentObject "(korma.core/select 'IncidentObject (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-IncidentStatus "(korma.core/select 'IncidentStatus (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-IncidentTask "(korma.core/select 'IncidentTask (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-IncidentType "(korma.core/select 'IncidentType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Job "(korma.core/select 'Job (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :NextRunOn :Status))"
:et-JobRun "(korma.core/select 'JobRun (korma.core/fields :CreatedOn :DeletedOn :EndedOn :Id :ModifiedOn :StartedOn :Status))"
:et-LDAPAction "(korma.core/select 'LDAPAction (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-LDAPConfig "(korma.core/select 'LDAPConfig (korma.core/fields :BaseDN :CreatedOn :DeletedOn :Domain :Id :ModifiedOn :Password :ServerName :Username))"
:et-LDAPType "(korma.core/select 'LDAPType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Likelihood "(korma.core/select 'Likelihood (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :UpperThreshold :Value))"
:et-Manufacturer "(korma.core/select 'Manufacturer (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-MitigationStatus "(korma.core/select 'MitigationStatus (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Network "(korma.core/select 'Network (korma.core/fields :Abbreviation :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Note "(korma.core/select 'Note (korma.core/fields :CreatedOn :DeletedOn :Format :Id :ModifiedOn :ResponseTo_NoteId :Subject :Type))"
:et-Notification "(korma.core/select 'Notification (korma.core/fields :CreatedOn :DeletedOn :Failed :Id :MailBatchNumber :ModifiedOn :SentOn :SubjectLine))"
:et-NotificationRule "(korma.core/select 'NotificationRule (korma.core/fields :Active :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :On_Condition :On_DaysFromDate :SendToApprover :SendToPerformer :SendToProjectCreator :SendToReviewer))"
:et-NotificationRuleSet "(korma.core/select 'NotificationRuleSet (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-NotificationType "(korma.core/select 'NotificationType (korma.core/fields :CreatedOn :DeletedOn :Description :EmailPriority :Id :ModifiedOn :Name :SubjectPrefix))"
:et-OperatingSystem "(korma.core/select 'OperatingSystem (korma.core/fields :Build :CreatedOn :DeletedOn :Family :Flavor :Id :ModifiedOn :Name :OriginalName :ServicePack :Version))"
:et-OperatingSystemType "(korma.core/select 'OperatingSystemType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Outcome "(korma.core/select 'Outcome (korma.core/fields :ApprovalRequired :BackColorName :CommentsRequired :CreatedOn :DeletedOn :Description :FixedEntry :ForeColorName :Id :ModifiedOn :Name))"
:et-Person "(korma.core/select 'Person (korma.core/fields :CellPhone :CreatedOn :DeletedOn :DisableASLMLogin :DisableLDAPLogin :DisableWebLogin :Email :ExpiresOn :FirstName :ForcePasswordReset :Id :IsGlobalUser :IsRestrictedUser :IsSuperuser :IsSystemUser :LastLoginFrom :LastLoginOn :LastLogoutOn :LastName :LDAPGUID :MiddleName :ModifiedOn :Password :PasswordLastSetOn :Suffix :Title :Username :WorkPhone))"
:et-Person_History "(korma.core/select 'Person_History (korma.core/fields :AddressId :CellPhone :CreatedOn :DeletedOn :DisableASLMLogin :DisableLDAPLogin :DisableWebLogin :Email :ExpiresOn :FirstName :ForcePasswordReset :Id :IsGlobalUser :IsRestrictedUser :IsSuperuser :IsSystemUser :LastLoginFrom :LastLoginOn :LastLogoutOn :LastName :LDAPConfigId :LDAPGUID :MiddleName :ModifiedOn :Password :PasswordLastSetOn :Suffix :Title :Username :WorkPhone))"
:et-PersonLDAPEvent "(korma.core/select 'PersonLDAPEvent (korma.core/fields :Completed :CreatedOn :DeletedOn :Description :Id :Message :ModifiedOn :PersonId))"
:et-PersonPasswordHistory "(korma.core/select 'PersonPasswordHistory (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Password :Username))"
:et-PersonPerson "(korma.core/select 'PersonPerson (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PersonRelationshipType "(korma.core/select 'PersonRelationshipType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Performer "(korma.core/select 'Performer (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PhysicalAsset "(korma.core/select 'PhysicalAsset (korma.core/fields :ContractEndOn :ContractNumber :ContractStartOn :CreatedOn :DeletedOn :EndOfLifeOn :ExternalKey :Id :InstalledOn :Location :ModifiedOn :PartNumber :PurchasedOn :SerialNumber :ServiceTag))"
:et-Policy "(korma.core/select 'Policy (korma.core/fields :AddDotZero :AllowExceptionRequest :AllowPDFDownload :CreatedOn :DeletedOn :Description :Guid :Id :InvitationOnly :Keywords :ModifiedOn :Name :NextReviewOn :NumberFormat :Prefix :RequireAcceptance :Version))"
:et-PolicyAcceptance "(korma.core/select 'PolicyAcceptance (korma.core/fields :CreatedOn :DeletedOn :EnteredOn :Id :ModifiedOn))"
:et-PolicyExceptionRequest "(korma.core/select 'PolicyExceptionRequest (korma.core/fields :CreatedOn :DeletedOn :ExpiresOn :Id :ModifiedOn :SubmittedOn))"
:et-PolicyExceptionRequestStatus "(korma.core/select 'PolicyExceptionRequestStatus (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-PolicyPublishEvent "(korma.core/select 'PolicyPublishEvent (korma.core/fields :CreatedOn :DeletedOn :Id :IsPublic :ModifiedOn :PublishedPolicyName))"
:et-PolicyReference "(korma.core/select 'PolicyReference (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicySection "(korma.core/select 'PolicySection (korma.core/fields :AutoNumber :CreatedOn :DeletedOn :Guid :HideNumber :Id :Keywords :ModifiedOn :Name :Number :SortKey :UCFControlNumber))"
:et-PolicySectionPolicySection "(korma.core/select 'PolicySectionPolicySection (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicySectionReference "(korma.core/select 'PolicySectionReference (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicySectionRole "(korma.core/select 'PolicySectionRole (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicySectionStandardComponent "(korma.core/select 'PolicySectionStandardComponent (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicySectionText "(korma.core/select 'PolicySectionText (korma.core/fields :CreatedOn :DeletedOn :EnteredOn :Id :ModifiedOn))"
:et-PolicyStandardComponent "(korma.core/select 'PolicyStandardComponent (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicyStatus "(korma.core/select 'PolicyStatus (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-PolicyTask "(korma.core/select 'PolicyTask (korma.core/fields :CreatedOn :DeletedOn :DueOn :Guid :Id :ModifiedOn :Round))"
:et-PolicyTaskEvent "(korma.core/select 'PolicyTaskEvent (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-PolicyTaskOutcome "(korma.core/select 'PolicyTaskOutcome (korma.core/fields :BackColorName :CommentsRequired :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-PolicyTaskStatus "(korma.core/select 'PolicyTaskStatus (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-PolicyTaskType "(korma.core/select 'PolicyTaskType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-PolicyTemplate "(korma.core/select 'PolicyTemplate (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-PolicyType "(korma.core/select 'PolicyType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Priority "(korma.core/select 'Priority (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :FixedEntry :ForeColorName :Id :ModifiedOn :Name))"
:et-Procedure "(korma.core/select 'Procedure (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Project "(korma.core/select 'Project (korma.core/fields :CreatedOn :DeletedOn :Description :ExpiresOn :Id :IsHistorical :ModifiedOn :Name :ProjectStartDate :SortKey :TaskDueDate))"
:et-ProjectNotification "(korma.core/select 'ProjectNotification (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-ProjectType "(korma.core/select 'ProjectType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Protocol "(korma.core/select 'Protocol (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Recurrence "(korma.core/select 'Recurrence (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Reference "(korma.core/select 'Reference (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :URL :URLTemplate))"
:et-ReferenceType "(korma.core/select 'ReferenceType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Report "(korma.core/select 'Report (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Name :Title))"
:et-ReportConfig "(korma.core/select 'ReportConfig (korma.core/fields :Category :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-ResourceCost "(korma.core/select 'ResourceCost (korma.core/fields :CreatedOn :DeletedOn :EffectiveDate :Id :ModifiedOn :PerDiemCost))"
:et-RiskLevel "(korma.core/select 'RiskLevel (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :UpperThreshold))"
:et-Role "(korma.core/select 'Role (korma.core/fields :Abbreviation :CreatedOn :DeletedOn :Description :FilterByAssetType :FilterByNetwork :Flags :Id :ModifiedOn :Name))"
:et-RoleModule "(korma.core/select 'RoleModule (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :ModuleNumber :ReadAccess :WriteAccess))"
:et-Service "(korma.core/select 'Service (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-Severity "(korma.core/select 'Severity (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :Number :Probability))"
:et-Software "(korma.core/select 'Software (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-StandardComponent "(korma.core/select 'StandardComponent (korma.core/fields :Abbreviation :AltKey :AutoNumber :CreatedOn :DeletedOn :EffectiveDate :Flags :HideNumber :Id :IsDomain :IsTask :ModifiedOn :Name :Number :SortKey :UCFControlNumber :Version))"
:et-StandardComponentCoverageLink "(korma.core/select 'StandardComponentCoverageLink (korma.core/fields :Comments :Coverage :CreatedOn :DeletedOn :Id :Manual :ModifiedOn))"
:et-StandardComponentTask "(korma.core/select 'StandardComponentTask (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-StandardComponentVendorProduct "(korma.core/select 'StandardComponentVendorProduct (korma.core/fields :Comments :Coverage :CreatedOn :DeletedOn :Id :Manual :ModifiedOn))"
:et-StandardComponentVulnerability "(korma.core/select 'StandardComponentVulnerability (korma.core/fields :Comments :Coverage :CreatedOn :DeletedOn :Id :Manual :ModifiedOn))"
:et-StandardComponentWeight "(korma.core/select 'StandardComponentWeight (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :Value))"
:et-Standard "(korma.core/select 'Standard (korma.core/fields :Abbreviation :AutoNumber :CreatedOn :DeletedOn :Description :DescriptionTitle :Id :IssuerName :ModifiedOn :Name :ObjectivesTitle :Originator :ParentCategory :ProceduresTitle :ReferencesTitle :RemediationTitle :ShowAssetColumn))"
:et-Subnet "(korma.core/select 'Subnet (korma.core/fields :AddressRange :CreatedOn :DeletedOn :Description :FirstInRange :Id :LastInRange :ModifiedOn :Name))"
:et-SubnetExposure "(korma.core/select 'SubnetExposure (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-Survey "(korma.core/select 'Survey (korma.core/fields :CreatedOn :DeletedOn :Description :EnableAttachAssets :EnableAttachDocuments :Id :ModifiedOn :Name :RequireComments))"
:et-SurveySection "(korma.core/select 'SurveySection (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :Question :SortKey :Title :Type))"
:et-SurveySectionChoice "(korma.core/select 'SurveySectionChoice (korma.core/fields :Choice :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-Task "(korma.core/select 'Task (korma.core/fields :AssignTo :ConfigGUID :CreatedOn :DeletedOn :ExternalKey :Id :IsCanceled :ModifiedOn :Name :SentOn :SentStatus :SentTo :SortKey :TaskGUID))"
:et-TaskPerformance "(korma.core/select 'TaskPerformance (korma.core/fields :CreatedOn :DeletedOn :DueOn :Id :ModifiedOn))"
:et-TaskPerformanceEvent "(korma.core/select 'TaskPerformanceEvent (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn))"
:et-TaskPerformancePerformer "(korma.core/select 'TaskPerformancePerformer (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn :TaskRole))"
:et-TaskPerformanceNote "(korma.core/select 'TaskPerformanceNote (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskPerformanceNotification "(korma.core/select 'TaskPerformanceNotification (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskPerformanceObject "(korma.core/select 'TaskPerformanceObject (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskPerformanceStatus "(korma.core/select 'TaskPerformanceStatus (korma.core/fields :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name))"
:et-TaskResult "(korma.core/select 'TaskResult (korma.core/fields :CreatedOn :DeletedOn :EnteredOn :ExpiresOn :Id :ModifiedOn))"
:et-TaskResultEffort "(korma.core/select 'TaskResultEffort (korma.core/fields :CreatedOn :DeletedOn :Hours :Id :ModifiedOn))"
:et-TaskResultExpense "(korma.core/select 'TaskResultExpense (korma.core/fields :Amount :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskResultLineage "(korma.core/select 'TaskResultLineage (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskResultObject "(korma.core/select 'TaskResultObject (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskResultOutcome "(korma.core/select 'TaskResultOutcome (korma.core/fields :Approver_PersonId :CreatedOn :DeletedOn :ExpiresOn :Id :ModifiedOn))"
:et-TaskResultOutcomeApproval "(korma.core/select 'TaskResultOutcomeApproval (korma.core/fields :CreatedOn :Deadline :DeletedOn :Id :ModifiedOn))"
:et-TaskResultOutcomeNotification "(korma.core/select 'TaskResultOutcomeNotification (korma.core/fields :CreatedOn :DeletedOn :Id :ModifiedOn))"
:et-TaskResultScore "(korma.core/select 'TaskResultScore (korma.core/fields :Abbreviation :BackColorName :CreatedOn :DeletedOn :Description :ForeColorName :Id :ModifiedOn :Name :NormalizedScore :Probability :Score))"
:et-TaskResultScoreSet "(korma.core/select 'TaskResultScoreSet (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-TaskResultStatus "(korma.core/select 'TaskResultStatus (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-TaskResultType "(korma.core/select 'TaskResultType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-TaskType "(korma.core/select 'TaskType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-TechnicalScan "(korma.core/select 'TechnicalScan (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name :ScanDate))"
:et-TechnicalScanType "(korma.core/select 'TechnicalScanType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-TimeZone "(korma.core/select 'TimeZone (korma.core/fields :CreatedOn :DeletedOn :Description :GMTOffsetMinutes :Id :ModifiedOn :Name))"
:et-Vendor "(korma.core/select 'Vendor (korma.core/fields :Abbreviation :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-VendorProduct "(korma.core/select 'VendorProduct (korma.core/fields :CreatedOn :DeletedOn :Deployment :Description :Id :ModifiedOn :Name :Number :Price))"
:et-Vulnerability "(korma.core/select 'Vulnerability (korma.core/fields :CreatedOn :DeletedOn :Id :IsIgnored :LastUpdatedOn :ManualSeverity :ModifiedOn :Name :PatchAvailable :PatchReleasedOn :ReleasedOn :UCFControlNumber))"
:et-Vulnerability_History "(korma.core/select 'Vulnerability_History (korma.core/fields :Comments :CreatedOn :DeletedOn :Id :IsIgnored :ModifiedOn))"
:et-VulnerabilityReference "(korma.core/select 'VulnerabilityReference (korma.core/fields :CreatedOn :CVSS_BaseScore :CVSS_BaseVector :CVSS_EnvironmentalScore :CVSS_EnvironmentalVector :CVSS_TemporalScore :CVSS_TemporalVector :DeletedOn :ExploitSubscore :Id :ImpactSubscore :IsPrimaryReferenceKey :ModifiedOn :ReferenceKey))"
:et-VulnerabilityRule "(korma.core/select 'VulnerabilityRule (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-VulnerabilityRuleSet "(korma.core/select 'VulnerabilityRuleSet (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
:et-VulnerabilityType "(korma.core/select 'VulnerabilityType (korma.core/fields :CreatedOn :DeletedOn :Description :Id :ModifiedOn :Name))"
})
