(ns alexa-to-aurora.sql-select-join-tables
  (:require [datomic.api :as d])
 )

(def sql-select-join-tables
{
:et-AnalysisAsset "(korma.core/select 'AnalysisAsset (korma.core/fields :AnalysisId :AssetId :Id))"
:et-AnalysisAssetFilter "(korma.core/select 'AnalysisAssetFilter (korma.core/fields :AnalysisId :AssetFilterId :Id))"
:et-AnalysisAssetGroup "(korma.core/select 'AnalysisAssetGroup (korma.core/fields :AnalysisId :AssetGroupId :Id))"
:et-AnalysisExposureCategory "(korma.core/select 'AnalysisExposureCategory (korma.core/fields :AnalysisId :ExposureCategoryId :Id))"
:et-AnalysisProject "(korma.core/select 'AnalysisProject (korma.core/fields :AnalysisId :Id :ProjectId))"
:et-AnalysisTechnicalScan "(korma.core/select 'AnalysisTechnicalScan (korma.core/fields :AnalysisId :Id :TechnicalScanId))"
:et-AssetExposureMitigationStatusTask "(korma.core/select 'AssetExposureMitigationStatusTask (korma.core/fields :AssetExposureMitigationStatusId :Id :TaskId))"
:et-AssetExposureTechnicalScan "(korma.core/select 'AssetExposureTechnicalScan (korma.core/fields :AssetExposureId :Id :TechnicalScanId))"
:et-AssetFilterAssetClass "(korma.core/select 'AssetFilterAssetClass (korma.core/fields :AssetClassId :AssetFilterId :Id))"
:et-AssetFilterAssetType "(korma.core/select 'AssetFilterAssetType (korma.core/fields :AssetFilterId :AssetTypeId :Id))"
:et-AssetFilterImpact "(korma.core/select 'AssetFilterImpact (korma.core/fields :AssetFilterId :Id :ImpactId))"
:et-AssetFilterOperatingSystem "(korma.core/select 'AssetFilterOperatingSystem (korma.core/fields :AssetFilterId :Id :OperatingSystemId))"
:et-AssetFilterStandard "(korma.core/select 'AssetFilterStandard (korma.core/fields :AssetFilterId :Id :StandardId))"
:et-AssetGroupAsset "(korma.core/select 'AssetGroupAsset (korma.core/fields :AssetGroupId :AssetId :Id))"
:et-AssetGroupAttributeValue "(korma.core/select 'AssetGroupAttributeValue (korma.core/fields :AssetGroupId :AttributeValueId :Id))"
:et-AssetGroupBusinessUnit "(korma.core/select 'AssetGroupBusinessUnit (korma.core/fields :AssetGroupId :BusinessUnitId :Id))"
:et-AssetGroupDataType "(korma.core/select 'AssetGroupDataType (korma.core/fields :AssetGroupId :DataTypeId :Id))"
:et-AssetGroupPerson "(korma.core/select 'AssetGroupPerson (korma.core/fields :AssetGroupId :Id :PersonId))"
:et-AssetSoftware "(korma.core/select 'AssetSoftware (korma.core/fields :AssetId :Id :SoftwareId))"
:et-AssetDataType "(korma.core/select 'AssetDataType (korma.core/fields :AssetId :DataTypeId :Id))"
:et-AssetAttributeValue "(korma.core/select 'AssetAttributeValue (korma.core/fields :AssetId :AttributeValueId :Id))"
:et-AssetTypeRole "(korma.core/select 'AssetTypeRole (korma.core/fields :AssetTypeId :Id :RoleId))"
:et-AssetVulnerabilityMitigationStatusTask "(korma.core/select 'AssetVulnerabilityMitigationStatusTask (korma.core/fields :AssetVulnerabilityMitigationStatusId :Id :TaskId))"
:et-AuditPlanProject "(korma.core/select 'AuditPlanProject (korma.core/fields :AuditPlanId :Id :ProjectId))"
:et-AuditPlanRole "(korma.core/select 'AuditPlanRole (korma.core/fields :AuditPlanId :Id :RoleId))"
:et-AuditPlanStandardComponent "(korma.core/select 'AuditPlanStandardComponent (korma.core/fields :AuditPlanId :Id :StandardComponentId))"
:et-BusinessUnitAttributeValue "(korma.core/select 'BusinessUnitAttributeValue (korma.core/fields :AttributeValueId :BusinessUnitId :Id))"
:et-DataFindingRuleDataType "(korma.core/select 'DataFindingRuleDataType (korma.core/fields :DataFindingRuleId :DataTypeId :Id))"
:et-DataFindingMitigationStatusTask "(korma.core/select 'DataFindingMitigationStatusTask (korma.core/fields :DataFindingMitigationStatusId :Id :TaskId))"
:et-DataLocationPerson "(korma.core/select 'DataLocationPerson (korma.core/fields :DataLocationId :Id :PersonId))"
:et-IncidentAsset "(korma.core/select 'IncidentAsset (korma.core/fields :AssetId :Id :IncidentId))"
:et-IncidentAssetGroup "(korma.core/select 'IncidentAssetGroup (korma.core/fields :AssetGroupId :Id :IncidentId))"
:et-IncidentAttributeValue "(korma.core/select 'IncidentAttributeValue (korma.core/fields :AttributeValueId :Id :IncidentId))"
:et-IncidentBusinessUnit "(korma.core/select 'IncidentBusinessUnit (korma.core/fields :BusinessUnitId :Id :IncidentId))"
:et-IncidentDataFinding "(korma.core/select 'IncidentDataFinding (korma.core/fields :DataFindingId :Id :IncidentId))"
:et-IncidentDomain "(korma.core/select 'IncidentDomain (korma.core/fields :DomainComponentId :Id :IncidentId))"
:et-IncidentStandard "(korma.core/select 'IncidentStandard (korma.core/fields :Id :IncidentId :StandardId))"
:et-NetworkRole "(korma.core/select 'NetworkRole (korma.core/fields :Id :NetworkId :RoleId))"
:et-NotificationRulePerson "(korma.core/select 'NotificationRulePerson (korma.core/fields :Id :NotificationRuleId :PersonId))"
:et-NotificationRuleRole "(korma.core/select 'NotificationRuleRole (korma.core/fields :Id :NotificationRuleId :RoleId))"
:et-PolicyBusinessUnit "(korma.core/select 'PolicyBusinessUnit (korma.core/fields :BusinessUnitId :Id :PolicyId))"
:et-PolicyTaskNotification "(korma.core/select 'PolicyTaskNotification (korma.core/fields :Id :NotificationId :PolicyTaskId))"
:et-ProjectAttributeValue "(korma.core/select 'ProjectAttributeValue (korma.core/fields :AttributeValueId :Id :ProjectId))"
:et-ProjectBusinessUnit "(korma.core/select 'ProjectBusinessUnit (korma.core/fields :BusinessUnitId :Id :ProjectId))"
:et-ProjectIncident "(korma.core/select 'ProjectIncident (korma.core/fields :Id :IncidentId :ProjectId))"
:et-ProjectRole "(korma.core/select 'ProjectRole (korma.core/fields :Id :ProjectId :RoleId))"
:et-SoftwareDataType "(korma.core/select 'SoftwareDataType (korma.core/fields :DataTypeId :Id :SoftwareId))"
:et-StandardComponentPerson "(korma.core/select 'StandardComponentPerson (korma.core/fields :Id :PersonId :StandardComponentId))"
:et-StandardAsset "(korma.core/select 'StandardAsset (korma.core/fields :AssetId :Id :StandardId))"
:et-StandardAttributeValue "(korma.core/select 'StandardAttributeValue (korma.core/fields :AttributeValueId :Id :StandardId))"
:et-StandardDataType "(korma.core/select 'StandardDataType (korma.core/fields :DataTypeId :Id :StandardId))"
:et-SubnetStandard "(korma.core/select 'SubnetStandard (korma.core/fields :Id :StandardId :SubnetId))"
:et-SurveySectionRole "(korma.core/select 'SurveySectionRole (korma.core/fields :Id :RoleId :SurveySectionId))"
:et-SurveySectionStandardComponent "(korma.core/select 'SurveySectionStandardComponent (korma.core/fields :Id :StandardComponentId :SurveySectionId))"
:et-TaskNotification "(korma.core/select 'TaskNotification (korma.core/fields :Id :NotificationId :TaskId))"
:et-TaskPerformanceLineage "(korma.core/select 'TaskPerformanceLineage (korma.core/fields :Id :NewTaskPerformanceId :OldTaskPerformanceId))"
:et-TaskResultOutcomeTask "(korma.core/select 'TaskResultOutcomeTask (korma.core/fields :Id :TaskId :TaskResultOutcomeId))"
:et-TaskResultTechnicalScan "(korma.core/select 'TaskResultTechnicalScan (korma.core/fields :Id :TaskResultId :TechnicalScanId))"
})
