(ns alexa-to-aurora.sql-select-foreign-keys
  (:require [datomic.api :as d])
 )

(def sql-select-foreign-keys
{
:et-Address "(korma.core/select 'Address (korma.core/fields :CountryId :Id :TimeZoneId))"
:et-Address_History "(korma.core/select 'Address_History (korma.core/fields :AddressId :Id :LoginPersonId))"
:et-Analysis "(korma.core/select 'Analysis (korma.core/fields :AnalysisBasisId :AnalysisMethodId :AnalysisTypeId :CreatedBy_PersonId :Id))"
:et-AnalysisAnalysis "(korma.core/select 'AnalysisAnalysis (korma.core/fields :AnalysisId :BasisAnalysisId :Id))"
:et-AnalysisAssetLikelihood "(korma.core/select 'AnalysisAssetLikelihood (korma.core/fields :AnalysisId :AssetId :ExposureId :Id :ImpactId :LikelihoodId :Manual_LikelihoodId :Manual_PersonId :ProjectId :RiskLevelId :TechnicalScanId))"
:et-AnalysisAssetVulnSeverity "(korma.core/select 'AnalysisAssetVulnSeverity (korma.core/fields :AnalysisId :AssetTypeId :Id :NetworkId :OperatingSystemId :SeverityId))"
:et-AnalysisBasis "(korma.core/select 'AnalysisBasis (korma.core/fields :AnalysisTypeId :Id))"
:et-AnalysisComponentScore "(korma.core/select 'AnalysisComponentScore (korma.core/fields :AnalysisId :BusinessUnitId :Id :StandardComponentId))"
:et-AnalysisExpense "(korma.core/select 'AnalysisExpense (korma.core/fields :AnalysisId :CurrencyId :ExpenseCategoryId :Id))"
:et-AnalysisMethod "(korma.core/select 'AnalysisMethod (korma.core/fields :AnalysisTypeId :Id))"
:et-Asset "(korma.core/select 'Asset (korma.core/fields :AssetClassId :AssetTypeId :Custodian_PersonId :Id :ImpactId :NetworkId :OperatingSystemId :Owner_PersonId :PhysicalAssetId))"
:et-Asset_History "(korma.core/select 'Asset_History (korma.core/fields :AssetClassId :AssetId :AssetTypeId :ChangedBy_PersonId :Custodian_PersonId :Id :ImpactId :NetworkId :Owner_PersonId))"
:et-AssetExposure "(korma.core/select 'AssetExposure (korma.core/fields :AssetId :ExposureId :Id :ProtocolId :ServiceId :VulnerabilityId))"
:et-AssetExposureMitigationStatus "(korma.core/select 'AssetExposureMitigationStatus (korma.core/fields :AssetExposureId :ExplanationId :Id :MitigationStatusId :PersonId))"
:et-AssetFilter "(korma.core/select 'AssetFilter (korma.core/fields :CustodianPersonId :Id :NetworkId :OwnerPersonId :SubnetId))"
:et-AssetGroup "(korma.core/select 'AssetGroup (korma.core/fields :AssetGroupTypeId :Id :NetworkId :SubnetId))"
:et-AssetGroupBusinessMetric "(korma.core/select 'AssetGroupBusinessMetric (korma.core/fields :AssetGroupId :BusinessMetricId :Id))"
:et-AssetImpact "(korma.core/select 'AssetImpact (korma.core/fields :AssetId :Id :ImpactId :ImpactTypeId))"
:et-AssetClass "(korma.core/select 'AssetClass (korma.core/fields :Id :ImpactId))"
:et-AssetVulnerability "(korma.core/select 'AssetVulnerability (korma.core/fields :AssetId :Id :ProtocolId :ServiceId :VulnerabilityId))"
:et-AssetVulnerabilityAddendum "(korma.core/select 'AssetVulnerabilityAddendum (korma.core/fields :AssetVulnerabilityId :Id :TechnicalScanId))"
:et-AssetVulnerabilityMitigationStatus "(korma.core/select 'AssetVulnerabilityMitigationStatus (korma.core/fields :AssetVulnerabilityId :ExplanationId :Id :MitigationStatusId :PersonId))"
:et-AssetVulnerabilityTechnicalScan "(korma.core/select 'AssetVulnerabilityTechnicalScan (korma.core/fields :AssetVulnerabilityId :DetectionStatusId :DetectionTypeId :Id :TechnicalScanId))"
:et-Attribute "(korma.core/select 'Attribute (korma.core/fields :AttributeValueScopeId :AttributeValueTypeId :Id))"
:et-AttributeValue "(korma.core/select 'AttributeValue (korma.core/fields :AttributeId :Id))"
:et-AuditPlan "(korma.core/select 'AuditPlan (korma.core/fields :Author_PersonId :Id))"
:et-BusinessMetric "(korma.core/select 'BusinessMetric (korma.core/fields :AttributeValueTypeId :CreatedBy_PersonId :CurrencyId :EntityTypeId :Id :RecurrenceId))"
:et-BusinessUnit "(korma.core/select 'BusinessUnit (korma.core/fields :AddressId :DefaultCurrencyId :Id))"
:et-BusinessUnitBusinessMetric "(korma.core/select 'BusinessUnitBusinessMetric (korma.core/fields :BusinessMetricId :BusinessUnitId :Id))"
:et-BusinessUnitBusinessUnit "(korma.core/select 'BusinessUnitBusinessUnit (korma.core/fields :BusinessUnitAId :BusinessUnitBId :BusinessUnitRelationshipTypeId :Id))"
:et-CurrencyExchange "(korma.core/select 'CurrencyExchange (korma.core/fields :CurrencyId :Id))"
:et-DataFinding "(korma.core/select 'DataFinding (korma.core/fields :ContentTypeId :DataFindingRuleId :DataFindingSourceTypeId :DataLocationId :Id :SeverityId))"
:et-DataFindingAddendum "(korma.core/select 'DataFindingAddendum (korma.core/fields :DataFindingId :Id))"
:et-DataFindingMitigationStatus "(korma.core/select 'DataFindingMitigationStatus (korma.core/fields :DataFindingId :Id :MitigationStatusId))"
:et-DataFindingTechnicalScan "(korma.core/select 'DataFindingTechnicalScan (korma.core/fields :DataFindingId :DetectionStatusId :DetectionTypeId :Id :TechnicalScanId))"
:et-DataLocation "(korma.core/select 'DataLocation (korma.core/fields :AssetId :DataLocationTypeId :Id))"
:et-DataType "(korma.core/select 'DataType (korma.core/fields :DataClassId :Id))"
:et-EventHistory "(korma.core/select 'EventHistory (korma.core/fields :EventModuleId :EventTypeId :Id :LoginPersonId))"
:et-Explanation "(korma.core/select 'Explanation (korma.core/fields :CreatedBy_PersonId :ExplanationCategoryId :Id :ModifiedBy_PersonId))"
:et-Incident "(korma.core/select 'Incident (korma.core/fields :Id :IncidentStatusId :IncidentTypeId))"
:et-IncidentField "(korma.core/select 'IncidentField (korma.core/fields :Id :IncidentTypeId))"
:et-IncidentFieldData "(korma.core/select 'IncidentFieldData (korma.core/fields :Id :IncidentFieldId :IncidentId))"
:et-IncidentImpact "(korma.core/select 'IncidentImpact (korma.core/fields :Id :ImpactId :ImpactTypeId :IncidentId))"
:et-IncidentIncidentStatus "(korma.core/select 'IncidentIncidentStatus (korma.core/fields :Id :IncidentId :IncidentStatusId :PersonId))"
:et-IncidentObject "(korma.core/select 'IncidentObject (korma.core/fields :AssetGroupId :AssetId :Id :IncidentId :PersonId :ProcedureId))"
:et-IncidentTask "(korma.core/select 'IncidentTask (korma.core/fields :Id :IncidentId :TaskId :TaskResultId))"
:et-JobRun "(korma.core/select 'JobRun (korma.core/fields :EventHistoryId :Id :JobId))"
:et-LDAPConfig "(korma.core/select 'LDAPConfig (korma.core/fields :Id :LDAPTypeId))"
:et-Manufacturer "(korma.core/select 'Manufacturer (korma.core/fields :AddressId :Id))"
:et-Note "(korma.core/select 'Note (korma.core/fields :From_PersonId :Id :To_PersonId))"
:et-Notification "(korma.core/select 'Notification (korma.core/fields :From_PersonId :Id :NotificationTypeId :To_PersonId))"
:et-NotificationRule "(korma.core/select 'NotificationRule (korma.core/fields :Id :NotificationRuleSetId :NotificationTypeId :On_OutcomeId :On_TaskResultScoreId :On_TaskResultStatusId :On_TaskResultTypeId :Task_BusinessUnitId :Task_PriorityId))"
:et-OperatingSystem "(korma.core/select 'OperatingSystem (korma.core/fields :Alias_OperatingSystemId :DefaultAssetClassId :DefaultAssetTypeId :DefaultImpactId :Id :OperatingSystemTypeId))"
:et-Outcome "(korma.core/select 'Outcome (korma.core/fields :Id :ProjectTypeId))"
:et-Person "(korma.core/select 'Person (korma.core/fields :AddressId :Id :LDAPConfigId))"
:et-Person_History "(korma.core/select 'Person_History (korma.core/fields :Id :LoginPersonId :PersonId))"
:et-PersonLDAPEvent "(korma.core/select 'PersonLDAPEvent (korma.core/fields :BusinessUnitId :Id :LDAPActionId :LDAPConfigId :RoleId))"
:et-PersonPasswordHistory "(korma.core/select 'PersonPasswordHistory (korma.core/fields :Id :PersonId))"
:et-PersonPerson "(korma.core/select 'PersonPerson (korma.core/fields :Id :PersonAId :PersonBId :PersonRelationshipTypeId))"
:et-Performer "(korma.core/select 'Performer (korma.core/fields :BusinessUnitId :Id :PersonId :RoleId))"
:et-PhysicalAsset "(korma.core/select 'PhysicalAsset (korma.core/fields :AddressId :Id :ManufacturerId))"
:et-Policy "(korma.core/select 'Policy (korma.core/fields :Id :Owner_PersonId :PolicyStatusId :PolicyTemplateId :PolicyTypeId))"
:et-PolicyAcceptance "(korma.core/select 'PolicyAcceptance (korma.core/fields :AcceptedBy_PersonId :Id :PolicyExceptionRequestId :PolicyId))"
:et-PolicyExceptionRequest "(korma.core/select 'PolicyExceptionRequest (korma.core/fields :Id :PolicyExceptionRequestStatusId :PolicyId :SubmittedBy_PersonId))"
:et-PolicyPublishEvent "(korma.core/select 'PolicyPublishEvent (korma.core/fields :Id :PDF_DataFileId :PersonId :PolicyId :PolicyStatusId))"
:et-PolicyReference "(korma.core/select 'PolicyReference (korma.core/fields :Id :PolicyId :ReferenceId))"
:et-PolicySection "(korma.core/select 'PolicySection (korma.core/fields :EditedBy_PersonId :Id :ParentId :PolicyId))"
:et-PolicySectionPolicySection "(korma.core/select 'PolicySectionPolicySection (korma.core/fields :Id :PolicySectionId :Related_PolicySectionId))"
:et-PolicySectionReference "(korma.core/select 'PolicySectionReference (korma.core/fields :Id :PolicySectionId :ReferenceId))"
:et-PolicySectionRole "(korma.core/select 'PolicySectionRole (korma.core/fields :Id :PolicySectionId :PolicyTaskTypeId :RoleId))"
:et-PolicySectionStandardComponent "(korma.core/select 'PolicySectionStandardComponent (korma.core/fields :Id :PolicySectionId :StandardComponentId))"
:et-PolicySectionText "(korma.core/select 'PolicySectionText (korma.core/fields :EnteredBy_PersonId :Id :PolicySectionId))"
:et-PolicyStandardComponent "(korma.core/select 'PolicyStandardComponent (korma.core/fields :Id :PolicyId :StandardComponentId))"
:et-PolicyTask "(korma.core/select 'PolicyTask (korma.core/fields :AssignedTo_PersonId :Id :PolicyId :PolicySectionId :PolicySectionTextId :PolicyTaskTypeId))"
:et-PolicyTaskEvent "(korma.core/select 'PolicyTaskEvent (korma.core/fields :Actor_PersonId :Id :PolicySectionTextId :PolicyTaskId :PolicyTaskOutcomeId :PolicyTaskStatusId))"
:et-PolicyTaskOutcome "(korma.core/select 'PolicyTaskOutcome (korma.core/fields :Id :PolicyTaskTypeId))"
:et-PolicyTemplate "(korma.core/select 'PolicyTemplate (korma.core/fields :CreatedBy_PersonId :Id))"
:et-Procedure "(korma.core/select 'Procedure (korma.core/fields :BusinessUnitId :Id))"
:et-Project "(korma.core/select 'Project (korma.core/fields :CreatedBy_PersonId :Id :ProjectTypeId :TaskNotificationRuleSetId :TaskPriorityId))"
:et-ProjectNotification "(korma.core/select 'ProjectNotification (korma.core/fields :Id :NotificationId :NotificationRuleId :ProjectId))"
:et-Reference "(korma.core/select 'Reference (korma.core/fields :DataFileId :Id :ReferenceTypeId))"
:et-Report "(korma.core/select 'Report (korma.core/fields :CreatedBy_PersonId :Id :ReferenceId :ReportConfigId))"
:et-ReportConfig "(korma.core/select 'ReportConfig (korma.core/fields :CreatedBy_PersonId :Id))"
:et-ResourceCost "(korma.core/select 'ResourceCost (korma.core/fields :BusinessUnitId :CurrencyId :Id :PersonId :RoleId))"
:et-RoleModule "(korma.core/select 'RoleModule (korma.core/fields :Id :RoleId))"
:et-StandardComponent "(korma.core/select 'StandardComponent (korma.core/fields :DomainComponentId :EditedBy_PersonId :Id :ParentId :StandardComponentWeightId :StandardId))"
:et-StandardComponentCoverageLink "(korma.core/select 'StandardComponentCoverageLink (korma.core/fields :CoveredStandardComponentId :CreatedBy_PersonId :EventHistoryId :Id :StandardComponentId))"
:et-StandardComponentTask "(korma.core/select 'StandardComponentTask (korma.core/fields :Domain_StandardComponentId :Id :StandardComponentId :SurveySectionId :TaskId :TaskResultScoreSetId))"
:et-StandardComponentVendorProduct "(korma.core/select 'StandardComponentVendorProduct (korma.core/fields :CreatedBy_PersonId :EventHistoryId :Id :StandardComponentId :VendorProductId))"
:et-StandardComponentVulnerability "(korma.core/select 'StandardComponentVulnerability (korma.core/fields :CreatedBy_PersonId :EventHistoryId :Id :StandardComponentId :VulnerabilityId))"
:et-Subnet "(korma.core/select 'Subnet (korma.core/fields :Id :NetworkId))"
:et-SubnetExposure "(korma.core/select 'SubnetExposure (korma.core/fields :ExposureCategoryId :ExposureId :Id :SubnetId))"
:et-Survey "(korma.core/select 'Survey (korma.core/fields :CreatedBy_PersonId :Id))"
:et-SurveySection "(korma.core/select 'SurveySection (korma.core/fields :Id :SurveyId))"
:et-SurveySectionChoice "(korma.core/select 'SurveySectionChoice (korma.core/fields :Id :SurveySectionId :ToSurveySectionId))"
:et-Task "(korma.core/select 'Task (korma.core/fields :Id :ProjectId :TaskTypeId))"
:et-TaskPerformance "(korma.core/select 'TaskPerformance (korma.core/fields :Id :NotificationRuleSetId :PerformerId :PriorityId :TaskId :TaskPerformanceStatusId))"
:et-TaskPerformanceEvent "(korma.core/select 'TaskPerformanceEvent (korma.core/fields :AssignedPerformerId :Id :LoginPersonId :PolicySectionTextId :PrevAssignedPerformerId :TaskPerformanceId :TaskPerformanceNoteId :TaskPerformanceNotificationId :TaskPerformanceStatusId :TaskResultId :TaskResultOutcomeApprovalId :TaskResultOutcomeId :TaskResultStatusId))"
:et-TaskPerformancePerformer "(korma.core/select 'TaskPerformancePerformer (korma.core/fields :Id :PerformerId :TaskPerformanceId))"
:et-TaskPerformanceNote "(korma.core/select 'TaskPerformanceNote (korma.core/fields :Id :NoteId :TaskPerformanceId))"
:et-TaskPerformanceNotification "(korma.core/select 'TaskPerformanceNotification (korma.core/fields :Id :NotificationId :NotificationRuleId :TaskPerformanceId))"
:et-TaskPerformanceObject "(korma.core/select 'TaskPerformanceObject (korma.core/fields :AssetGroupId :AssetId :Id :PersonId :ProcedureId :TaskPerformanceId))"
:et-TaskResult "(korma.core/select 'TaskResult (korma.core/fields :Id :PerformerId :TaskId :TaskPerformanceId :TaskResultScoreId :TaskResultStatusId :TaskResultTypeId))"
:et-TaskResultEffort "(korma.core/select 'TaskResultEffort (korma.core/fields :EffortCategoryId :Id :TaskResultId))"
:et-TaskResultExpense "(korma.core/select 'TaskResultExpense (korma.core/fields :CurrencyId :ExpenseCategoryId :Id :TaskResultId))"
:et-TaskResultLineage "(korma.core/select 'TaskResultLineage (korma.core/fields :Id :NewTaskResultId :OldTaskResultId :TaskPerformanceId))"
:et-TaskResultObject "(korma.core/select 'TaskResultObject (korma.core/fields :AssetGroupId :AssetId :Id :PersonId :ProcedureId :TaskResultId))"
:et-TaskResultOutcome "(korma.core/select 'TaskResultOutcome (korma.core/fields :Id :OutcomeId :Reviewer_PersonId :SpecifiedReviewer_PersonId :TaskResultId))"
:et-TaskResultOutcomeApproval "(korma.core/select 'TaskResultOutcomeApproval (korma.core/fields :ApprovalStatusId :Approver_PersonId :Id :SpecifiedApprover_PersonId :TaskResultOutcomeId))"
:et-TaskResultOutcomeNotification "(korma.core/select 'TaskResultOutcomeNotification (korma.core/fields :Id :NotificationId :NotificationRuleId :TaskResultOutcomeId))"
:et-TaskResultScore "(korma.core/select 'TaskResultScore (korma.core/fields :Id :TaskResultScoreSetId))"
:et-TaskResultScoreSet "(korma.core/select 'TaskResultScoreSet (korma.core/fields :Id :StandardId))"
:et-TechnicalScan "(korma.core/select 'TechnicalScan (korma.core/fields :Id :ReferenceId :TechnicalScanTypeId))"
:et-Vendor "(korma.core/select 'Vendor (korma.core/fields :AddressId :Id))"
:et-VendorProduct "(korma.core/select 'VendorProduct (korma.core/fields :CurrencyId :Id :VendorId))"
:et-Vulnerability "(korma.core/select 'Vulnerability (korma.core/fields :Id :SeverityId :VulnerabilityTypeId))"
:et-Vulnerability_History "(korma.core/select 'Vulnerability_History (korma.core/fields :ChangedBy_PersonId :Id :SeverityId :VulnerabilityId :VulnerabilityTypeId))"
:et-VulnerabilityReference "(korma.core/select 'VulnerabilityReference (korma.core/fields :Id :ReferenceId :VulnerabilityId))"
:et-VulnerabilityRule "(korma.core/select 'VulnerabilityRule (korma.core/fields :Id :VulnerabilityRuleSetId))"
})
